// End-to-end browser integration with a synthetic relay. No paid API is contacted.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import {chromium} from 'playwright';
const root=process.cwd(),out=path.join(root,'.scratch-web','browser');await fs.mkdir(out,{recursive:true});
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.svg':'image/svg+xml'};
const server=http.createServer(async(req,res)=>{try{let url=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(url.endsWith('/'))url+='index.html';const f=path.resolve(root,'.'+url);if(!f.startsWith(root+path.sep))throw Error('outside root');const data=await fs.readFile(f);res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);}catch{res.writeHead(404);res.end('not found');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
let browser;try{browser=await chromium.launch({channel:'chrome',headless:true});}catch{browser=await chromium.launch({channel:'msedge',headless:true});}
const results=[],errors=[],secret='fixture-only-do-not-use-key-729384',context=await browser.newContext({viewport:{width:1440,height:1050}});
context.on('page',page=>page.on('pageerror',e=>errors.push(e.message)));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function ready(page,mode='human'){await page.goto(base+'/challenge.html?mode='+mode);await page.waitForSelector('body[data-arena-ready="true"]',{timeout:15000});}
async function state(page){return page.evaluate(async()=>{const {publicGame}=await import('./arena-app.mjs');return publicGame.state();});}
async function configure(page){await page.fill('#username','浏览器合成测试');await page.fill('#apiUrl','https://relay.example/v1');await page.fill('#apiKey',secret);await page.click('#fetchModels');await page.waitForFunction(()=>document.getElementById('modelSelect').options.length>=3);await page.selectOption('#modelSelect','Qwen-fixture');await page.selectOption('#effort','high');}
function decision(request){const b=request.postDataJSON();assert.equal(b.reasoning_effort,'high');assert.equal(request.headers().authorization,'Bearer '+secret);assert(!request.postData().includes(secret));const packet=JSON.parse(b.messages.findLast(m=>m.role==='user').content),s=packet.observation;for(const k of ['seed','world','hidden','truth','harmful'])assert(!Object.hasOwn(s,k));return {packet,s,value:{revision:s.revision,action:s.phase==='council'?'next_day':'allow',...(s.phase==='council'?{policy:'balanced'}:{}),reason:'仅用于验证自动流程的合成决定，不是模型成绩。',p_threat:0.4}};}
const respond=(route,value)=>route.fulfill({status:200,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'},body:JSON.stringify({choices:[{message:{content:JSON.stringify(value)}}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15}})});
try{
 const human=await context.newPage();await ready(human);await human.screenshot({path:path.join(out,'desktop-human-setup.png'),fullPage:true});
 assert.equal(await human.locator('#aiConfig').isVisible(),false);await human.fill('#username','测试人类');await human.click('#start');await human.waitForSelector('#campaign:not([hidden])');assert.equal((await state(human)).revision,0);assert.equal(await human.locator('#arenaPortrait svg').count(),1);await human.click('#soundToggle');assert.equal(await human.locator('#soundToggle').getAttribute('aria-pressed'),'true');await human.click('[data-action="allow"]');assert.equal((await state(human)).revision,1);await human.screenshot({path:path.join(out,'desktop-human-dossier.png'),fullPage:true});results.push('Human start, action, original portrait and music control');await human.close();
 const page=await context.newPage();let held=[],calls=0;
 await page.route('https://relay.example/v1/**',async route=>{if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'}});if(route.request().method()==='GET')return route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'},body:JSON.stringify({data:[{id:'Qwen-fixture'},{id:'DeepSeek-fixture'},{id:'GLM-fixture'}]})});const data=decision(route.request());calls++;held.push({route,data});});
 await ready(page,'ai');await configure(page);await page.screenshot({path:path.join(out,'desktop-ai-setup.png'),fullPage:true});await page.click('#startAI');await page.waitForFunction(()=>Number(document.getElementById('requestCount').textContent)>0);assert.equal((await state(page)).revision,0);
 await page.click('#pauseAI');assert.equal(held.length,1);await respond(held[0].route,held[0].data.value);await wait(600);assert.equal((await state(page)).revision,0);assert.equal(calls,1);results.push('Pause holds in-flight response without advancing or new calls');
 await page.click('#pauseAI');await page.waitForFunction(async()=>{const {publicGame}=await import('./arena-app.mjs');return publicGame.state().revision===1;});await page.waitForFunction(()=>Number(document.getElementById('requestCount').textContent)>=2);for(let n=0;n<200&&held.length<2;n++)await wait(10);assert.equal(held.length,2);await page.click('#stopAI');const revision=(await state(page)).revision;try{await respond(held[1].route,held[1].data.value);}catch{}await wait(600);assert.equal((await state(page)).revision,revision);assert.equal(calls,2);results.push('Resume applies once; stop cancels and prevents late-response action');
 const storage=await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}));assert(!storage.includes(secret));await page.close();
 const full=await context.newPage();let recalled=false,investigated=false,fullCalls=0;
 await full.route('https://relay.example/v1/**',async route=>{if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'}});if(route.request().method()==='GET')return route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'},body:JSON.stringify({data:[{id:'Qwen-fixture'},{id:'DeepSeek-fixture'},{id:'GLM-fixture'}]})});const {s,value}=decision(route.request());fullCalls++;
 if(!recalled){recalled=true;return respond(route,{revision:s.revision,action:'recall',query:s.case.person_id});}
 if(!investigated&&s.available_tests.registry?.available){investigated=true;return respond(route,{revision:s.revision,action:'investigate',test:'registry',reason:'合成流程测试调查',memory:'此处只有公开事实。'});}
 return respond(route,value);});
 await ready(full,'ai');await configure(full);await full.click('#startAI');await full.waitForSelector('#postmortem:not([hidden])',{timeout:180000});await full.waitForFunction(()=>document.getElementById('runState').textContent.includes('本局结束'));
 const final=await state(full);assert(final.finished);assert(final.revision>10);assert(fullCalls>10);assert(recalled&&investigated);
 const report=await full.evaluate(async()=>{const {publicGame}=await import('./arena-app.mjs');return publicGame.report();});assert.equal(report.metadata.username,'浏览器合成测试');assert.equal(report.metadata.model,'Qwen-fixture');assert.equal(report.metadata.effort,'high');assert.equal(report.metadata.participant_type,'ai');
 const persisted=await full.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}));assert(!persisted.includes(secret));assert(!persisted.includes('"custom_prompt"'));assert.equal(await full.locator('#boardRows tr').count(),1);assert((await full.locator('#boardRows').innerText()).includes('Qwen-fixture'));
 await full.screenshot({path:path.join(out,'desktop-ai-report.png'),fullPage:true});results.push(`Continuous loop, recall, investigation, day advance, endgame report and local board (${fullCalls} mock calls, day ${final.day})`);
 await full.click('#humanMode');await full.fill('#username','切回人类');await full.click('#start');await full.click('[data-action="allow"]');assert.equal((await state(full)).revision,1);results.push('Switch modes without touching existing AI result');await full.close();
 const phone=await context.newPage();await phone.setViewportSize({width:390,height:844});await ready(phone,'ai');await phone.screenshot({path:path.join(out,'mobile-ai-setup.png'),fullPage:true});assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await phone.click('#humanMode');await phone.click('#start');await phone.screenshot({path:path.join(out,'mobile-human-dossier.png'),fullPage:true});assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));results.push('390px mobile setup and live dossier have no document horizontal overflow');
 assert.deepEqual(errors,[]);results.push('No browser page exceptions; API key absent from local/session storage');
 const result={passed:results.length,results,synthetic_relay:true,real_vendor_calls:0,errors,checked_at:new Date().toISOString()};await fs.writeFile(path.join(out,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}catch(e){console.error('BROWSER TEST FAILED',e);console.error('PAGE ERRORS',errors);for(const p of context.pages())try{console.error('URL',p.url(),'BODY',(await p.locator('body').innerText()).slice(0,6000));await p.screenshot({path:path.join(out,'failure.png'),fullPage:true});}catch{}process.exitCode=1;}
finally{await context.close();await browser.close();await new Promise(r=>server.close(r));}
